import type { RacePrompt } from './index.js';

const pairs = (text:string) => text.trim().split('\n').map(line=>line.split('|').map(value=>value.trim()));
const vocabulary = pairs(`
anchor|مرساة
apron|مئزر
arrow|سهم
artist|فنان
autumn|خريف
avenue|جادة
bakery|مخبز
balcony|شرفة
barrel|برميل
basket|سلة
beard|لحية
beetle|خنفساء
blanket|بطانية
blossom|زهرة
bracelet|سوار
branch|غصن
breeze|نسيم
brick|طوبة
bucket|دلو
button|زر
cabin|كوخ
cage|قفص
camel|جمل
candle|شمعة
carpet|سجادة
carrot|جزرة
castle|قلعة
cave|كهف
ceiling|سقف
chain|سلسلة
chalk|طباشير
cheek|خد
cherry|كرز
chestnut|كستناء
chimney|مدخنة
cliff|جرف
clover|برسيم
coat|معطف
coconut|جوز الهند
compass|بوصلة
coral|مرجان
courtyard|فناء
crane|رافعة
crocodile|تمساح
crown|تاج
cucumber|خيار
cushion|وسادة
dagger|خنجر
daisy|أقحوان
deer|غزال
desert|صحراء
diamond|ألماس
dictionary|قاموس
dolphin|دلفين
donkey|حمار
drawer|درج
drum|طبل
eagle|عقاب
earring|قرط
elbow|مرفق
envelope|ظرف
eyebrow|حاجب
falcon|صقر
feather|ريشة
fence|سياج
fern|سرخس
fig|تين
fireplace|موقد
flame|لهب
flour|دقيق
fog|ضباب
fountain|نافورة
fox|ثعلب
freedom|حرية
frost|صقيع
garlic|ثوم
gazelle|ظبي
ginger|زنجبيل
glacier|نهر جليدي
glove|قفاز
goat|ماعز
grape|عنب
hammer|مطرقة
harbor|ميناء
harvest|حصاد
hedgehog|قنفذ
helmet|خوذة
horizon|أفق
hut|عشة
hyena|ضبع
ink|حبر
island|جزيرة
jacket|سترة
jasmine|ياسمين
jewel|جوهرة
jug|إبريق
keeper|حارس
kettle|غلاية
kidney|كلية
kite|طائرة ورقية
ladder|سلم
lantern|فانوس
lawyer|محام
leather|جلد
lemon|ليمون
lentil|عدس
leopard|نمر
lettuce|خس
library|مكتبة
lightning|برق
lily|زنبق
lobster|كركند
lock|قفل
magnet|مغناطيس
marble|رخام
meadow|مرج
merchant|تاجر
mirror|مرآة
mosquito|بعوضة
mustard|خردل
necklace|قلادة
needle|إبرة
nest|عش
nutmeg|جوزة الطيب
oar|مجداف
olive|زيتون
onion|بصل
orchard|بستان
ostrich|نعامة
otter|قضاعة
oven|فرن
owl|بومة
oyster|محار
palace|قصر
parrot|ببغاء
peach|خوخ
peacock|طاووس
pearl|لؤلؤة
pebble|حصاة
pepper|فلفل
pigeon|حمامة
pillow|مخدة
plum|برقوق
pomegranate|رمان
pond|بركة
potato|بطاطا
pumpkin|يقطين
rabbit|أرنب
radish|فجل
rainbow|قوس قزح
raven|غراب
reed|قصب
reef|شعاب مرجانية
refrigerator|ثلاجة
ribbon|شريط
rope|حبل
rosemary|إكليل الجبل
saddle|سرج
saffron|زعفران
sail|شراع
scarf|وشاح
scissors|مقص
scorpion|عقرب
seagull|نورس
seal|فقمة
seed|بذرة
shadow|ظل
shell|صدفة
shield|درع
shovel|مجرفة
silk|حرير
snail|حلزون
sparrow|عصفور
spider|عنكبوت
spinach|سبانخ
spoon|ملعقة
squirrel|سنجاب
staircase|درج السلم
straw|قش
stream|جدول مائي
suitcase|حقيبة سفر
sunflower|دوار الشمس
swallow|سنونو
swan|بجعة
sword|سيف
tailor|خياط
tent|خيمة
thimble|كشتبان
thorn|شوكة
thunder|رعد
toad|علجوم
towel|منشفة
tractor|جرار
tray|صينية
trumpet|بوق
tulip|توليب
tunnel|نفق
turtle|سلحفاة
valley|واد
vase|مزهرية
velvet|مخمل
vinegar|خل
violin|كمان
volcano|بركان
walnut|جوز
waterfall|شلال
weasel|ابن عرس
whale|حوت
wheat|قمح
whistle|صفارة
willow|صفصاف
wing|جناح
wolf|ذئب
wool|صوف
wrist|رسغ
zebra|حمار وحشي
`);

const synonyms=pairs(`
سعيد|مسرور
حزين|كئيب
شجاع|جريء
جبان|هياب
جميل|حسن
قبيح|دميم
كبير|ضخم
صغير|ضئيل
سريع|عاجل
بطيء|متأن
قريب|دان
بعيد|ناء
عظيم|جليل
كريم|سخي
بخيل|شحيح
ذكي|فطن
غبي|بليد
قوي|متين
ضعيف|واهن
هادئ|ساكن
صاخب|ضاج
غاضب|ساخط
لطيف|ودود
قاس|فظ
كاذب|مخادع
واضح|جلي
غامض|مبهم
صعب|عسير
سهل|يسير
قديم|عتيق
جديد|حديث
طويل|مديد
قصير|مقتضب
واسع|فسيح
ضيق|محدود
نظيف|نقي
متسخ|قذر
مفيد|نافع
ضار|مؤذ
ثمين|نفيس
رخيص|بخس
فقير|معدم
غني|ثري
مريض|سقيم
معافى|سليم
جائع|طاو
عطشان|ظمآن
متعب|مرهق
نشيط|حيوي
كسول|خامل
حذر|يقظ
مهمل|متهاون
فصيح|بليغ
صامت|ساكت
مشرق|منير
مظلم|معتم
رطب|مبتل
جاف|يابس
لين|طري
صلب|قاس
عال|مرتفع
منخفض|هابط
ممتلئ|مليء
فارغ|خال
حقيقي|واقعي
خيالي|وهمي
مسموح|مباح
ممنوع|محظور
حب|ود
كره|بغض
خوف|وجل
أمل|رجاء
يأس|قنوط
فرح|سرور
حزن|أسى
دهشة|عجب
غضب|سخط
هدوء|سكينة
ضجيج|صخب
بيت|منزل
طريق|سبيل
بحر|يم
سيف|حسام
أسد|ليث
حصان|جواد
صديق|رفيق
عدو|خصم
علم|معرفة
ماء|مياه
نور|ضياء
ظلام|عتمة
ذهب|تبر
مال|نقود
وقت|زمن
عام|سنة
ساعد|عاون
رحل|غادر
وصل|بلغ
نظر|أبصر
سمع|أصغى
تكلم|تحدث
سأل|استفسر
أجاب|رد
ركض|جرى
جلس|قعد
وقف|قام
ضحك|قهقه
بكى|نحب
نام|رقد
استيقظ|صحا
أحب|عشق
كره|أبغض
فرح|ابتهج
حزن|اغتم
خاف|وجل
عرف|علم
فهم|أدرك
حفظ|صان
طلب|سأل
أعطى|منح
أخذ|تناول
وجد|عثر
فقد|أضاع
بدأ|شرع
انتهى|انقضى
عاد|رجع
ذهب|مضى
جمع|حشد
فرق|شتت
بنى|شيد
هدم|حطم
زرع|غرس
قطف|جنى
فتح|شرع
أغلق|أقفل
اشترى|ابتاع
ربح|كسب
خسر|فقد
زاد|نما
نقص|قل
نجح|أفلح
فشل|أخفق
انتصر|فاز
انهزم|خسر
أسرع|عجل
أبطأ|تمهل
تعب|أعيى
ارتاح|استراح
سكت|صمت
صاح|صرخ
تأمل|تدبر
تذكر|استحضر
نسي|سها
سامح|عفا
عاقب|جازى
مدح|أثنى
ذم|هجا
`);

const opposites=pairs(`
طويل|قصير
كبير|صغير
حار|بارد
قريب|بعيد
صعب|سهل
سريع|بطيء
قوي|ضعيف
غني|فقير
جميل|قبيح
جديد|قديم
واسع|ضيق
نظيف|متسخ
مرتفع|منخفض
ثقيل|خفيف
ممتلئ|فارغ
مفتوح|مغلق
مضيء|مظلم
رطب|جاف
ناعم|خشن
لين|صلب
سعيد|حزين
شجاع|جبان
كريم|بخيل
ذكي|غبي
نشيط|كسول
هادئ|صاخب
متفائل|متشائم
صادق|كاذب
عادل|ظالم
متواضع|متكبر
صبور|عجول
مؤدب|وقح
أمين|خائن
نافع|ضار
واضح|غامض
حاضر|غائب
موجود|مفقود
حي|ميت
مريض|معافى
جائع|شبعان
عطشان|ريان
مستيقظ|نائم
مسموح|ممنوع
مقبول|مرفوض
ممكن|مستحيل
صحيح|خاطئ
حقيقي|زائف
طبيعي|اصطناعي
محلي|عالمي
عام|خاص
خارجي|داخلي
أفقي|عمودي
فردي|جماعي
علني|سري
دائم|مؤقت
مستمر|متقطع
منتظم|عشوائي
مبكر|متأخر
أول|آخر
سابق|لاحق
أمام|خلف
فوق|تحت
داخل|خارج
يمين|يسار
شرق|غرب
شمال|جنوب
صعود|هبوط
دخول|خروج
بداية|نهاية
حياة|موت
نهار|ليل
صباح|مساء
شروق|غروب
صيف|شتاء
ربح|خسارة
نجاح|فشل
فوز|هزيمة
سلام|حرب
حب|كره
أمل|يأس
فرح|حزن
عدل|ظلم
صدق|كذب
أمانة|خيانة
شجاعة|جبن
كرم|بخل
قوة|ضعف
صحة|مرض
علم|جهل
نظام|فوضى
نظافة|قذارة
حرية|عبودية
اتحاد|انقسام
وفاق|خلاف
صداقة|عداوة
حضور|غياب
قبول|رفض
إيجاب|سلب
زيادة|نقصان
جمع|طرح
ضرب|قسمة
بناء|هدم
فتح|إغلاق
شراء|بيع
عطاء|أخذ
ذهاب|إياب
سؤال|جواب
حديث|صمت
ضحك|بكاء
عمل|راحة
تقدم|تراجع
إصلاح|إفساد
إحياء|إماتة
تبسيط|تعقيد
تقوية|إضعاف
توسيع|تضييق
تسخين|تبريد
تجفيف|ترطيب
تنوير|تعتيم
تذكير|إنساء
تشجيع|تثبيط
تصدير|استيراد
إرسال|استقبال
تحميل|تفريغ
حفظ|إتلاف
ربط|فك
شد|إرخاء
دفع|سحب
رفع|خفض
زرع|اقتلاع
مدح|ذم
ثواب|عقاب
طاعة|عصيان
رحمة|قسوة
رضا|سخط
طمأنينة|قلق
يقين|شك
وحدة|كثرة
وفرة|ندرة
غلاء|رخص
قمة|قاع
مقدمة|مؤخرة
منبع|مصب
بر|بحر
نفع|ضرر
أمن|خوف
رخاء|شدة
سهولة|صعوبة
بساطة|تعقيد
مرونة|جمود
سرعة|بطء
قرب|بعد
طول|قصر
اتساع|ضيق
عمق|ضحالة
كثافة|خفة
بياض|سواد
جمال|قبح
حداثة|قدم
`);

export const expandedWordBank:Record<string,RacePrompt[]>={};
const add=(slug:string,prompt:string,answers:string[]) => (expandedWordBank[slug]??=[]).push({prompt,answers});
for(const [english,arabic] of vocabulary){
  add('translate',`🌍 ترجم إلى العربية: ${english}`,[arabic]);
  add('fast-type',`⌨️ اكتب بالضبط: المعرفة تبدأ بكلمة ${arabic}`,[`المعرفة تبدأ بكلمة ${arabic}`]);
  add('word-order',`🔤 رتّب الكلمات لتبدأ بـ «تعلمت»: اليوم / تعلمت / ${arabic} / كلمة`,[`تعلمت اليوم كلمة ${arabic}`,`تعلمت كلمة ${arabic} اليوم`]);
  add('complete-word',`🧩 أكمل ترجمة ${english}: ${[...arabic].map((c,i)=>i===1?'_':c).join('')}`,[arabic]);
  add('letter-order',`🔡 رتّب حروف ترجمة ${english}: ${[...arabic].reverse().join(' / ')}`,[arabic]);
}
// Context identifies the intended sense, and alternate pair answers are merged.
const synonymAnswers=new Map<string,Set<string>>();
for(const [word,answer] of synonyms){
  for(const [a,b] of [[word,answer],[answer,word]]){
    const answers=synonymAnswers.get(a)||new Set<string>();
    answers.add(b);synonymAnswers.set(a,answers);
  }
}
for(const [word,answers] of synonymAnswers)add('synonyms',`📖 اذكر مرادفًا لكلمة «${word}»؟`,[...answers]);
for(const [word,answer] of opposites){
  add('antonyms',`↔️ ما ضد «${word}»؟`,[answer]);
  add('antonyms',`↔️ ما ضد «${answer}»؟`,[word]);
}
for(let i=1;i<=180;i++){
  const a=i+2,b=2+i%9;
  const family=i%4;
  const prompt=family===0?`🧠 عدد إذا ضربته في ${b} ثم أضفت ${b+1} صار ${a*b+b+1}. ما العدد؟`:family===1?`🧠 أكمل النمط: ${a}، ${a+b}، ${a+2*b}، ؟`:family===2?`🧠 لدي ${a} صناديق، في كل صندوق ${b} كرات. أعطيت صديقي ${b-1} كرة. كم بقي؟`:`🧠 أنا عدد بين ${a-1} و${a+1}. من أنا؟`;
  const answer=family===0||family===3?a:family===1?a+3*b:a*b-b+1;
  add('logic',prompt,[String(answer)]);
  add('riddles',prompt,[String(answer)]);
  const right=i%2===0;
  add('true-false',`✅❌ صح أم خطأ: حاصل ضرب ${a} في ${b} هو ${a*b+(right?0:1)}.`,right?['صح','صحيح']:['خطأ','غلط']);
  const question={prompt:`🔘 ما باقي قسمة ${a*b+i%b} على ${b}؟`,answers:[String(i%b)],choices:[String(i%b),String((i%b)+1),String((i%b)+2)]};
  (expandedWordBank['quick-choice']??=[]).push(question);
}
// Exact RGB channel comparisons, with no ambiguous equal maxima.
const colorNames=['الأحمر','الأخضر','الأزرق'];
for(let i=0;i<180;i++){
  const winner=i%3,channels=[30+i%30,50+i%40,70+i%50];
  channels[winner]=180+Math.floor(i/3);
  add('colors',`🎨 أي قناة هي الأقوى في اللون RGB(${channels.join(', ')})؟ الأحمر R أم الأخضر G أم الأزرق B؟`,[colorNames[winner],['red','green','blue'][winner],['R','G','B'][winner]]);
}
