import type { ImportedRaceQuestion } from "./imported-question-bank.js";

const logo = (slug: string) => `https://cdn.simpleicons.org/${slug}/FFFFFF`;
const question = (kind: "car" | "company", slug: string, answers: string[]): ImportedRaceQuestion => ({
  prompt: kind === "car" ? "🚘 ما اسم شركة السيارات صاحبة هذا الشعار؟" : "🏢 ما اسم الشركة صاحبة هذا الشعار؟",
  answers,
  mediaUrl: logo(slug),
});

export const visualLogoQuestionBank: Record<string, ImportedRaceQuestion[]> = {
  "car-logos": [
    question("car", "tesla", ["tesla", "تسلا", "تيسلا"]),
    question("car", "toyota", ["toyota", "تويوتا"]),
    question("car", "honda", ["honda", "هوندا"]),
    question("car", "ford", ["ford", "فورد"]),
    question("car", "bmw", ["bmw", "بي ام دبليو", "بي إم دبليو"]),
    question("car", "audi", ["audi", "اودي", "أودي"]),
    question("car", "porsche", ["porsche", "بورش", "بورشه"]),
    question("car", "ferrari", ["ferrari", "فيراري"]),
    question("car", "lamborghini", ["lamborghini", "لامبورغيني", "لامبورجيني"]),
    question("car", "volkswagen", ["volkswagen", "فولكس فاجن", "فولكس واجن"]),
    question("car", "nissan", ["nissan", "نيسان"]),
    question("car", "hyundai", ["hyundai", "هيونداي", "هونداي"]),
    question("car", "kia", ["kia", "كيا"]),
    question("car", "volvo", ["volvo", "فولفو"]),
    question("car", "mazda", ["mazda", "مازدا"]),
    question("car", "subaru", ["subaru", "سوبارو"]),
    question("car", "chevrolet", ["chevrolet", "شيفروليه", "شفروليه"]),
    question("car", "mitsubishi", ["mitsubishi", "ميتسوبيشي"]),
    question("car", "bugatti", ["bugatti", "بوغاتي", "بوجاتي"]),
    question("car", "jeep", ["jeep", "جيب"]),
    question("car", "maserati", ["maserati", "مازيراتي", "ماسراتي"]),
    question("car", "renault", ["renault", "رينو"]),
    question("car", "citroen", ["citroen", "سيتروين", "ستروين"]),
    question("car", "peugeot", ["peugeot", "بيجو"]),
    question("car", "bentley", ["bentley", "بنتلي"]),
    question("car", "rollsroyce", ["rolls royce", "rolls-royce", "رولز رويس"]),
  ],
  "company-logos": [
    question("company", "apple", ["apple", "ابل", "آبل"]),
    question("company", "google", ["google", "جوجل", "غوغل"]),
    question("company", "netflix", ["netflix", "نتفلكس", "نتفليكس"]),
    question("company", "spotify", ["spotify", "سبوتيفاي"]),
    question("company", "discord", ["discord", "ديسكورد", "دسكورد"]),
    question("company", "youtube", ["youtube", "يوتيوب"]),
    question("company", "instagram", ["instagram", "انستغرام", "انستقرام"]),
    question("company", "tiktok", ["tiktok", "تيك توك", "تيكتوك"]),
    question("company", "samsung", ["samsung", "سامسونج"]),
    question("company", "nvidia", ["nvidia", "انفيديا", "نفيديا"]),
    question("company", "intel", ["intel", "انتل", "إنتل"]),
    question("company", "amd", ["amd", "اي ام دي", "إيه إم دي"]),
    question("company", "paypal", ["paypal", "باي بال", "بايبال"]),
    question("company", "uber", ["uber", "اوبر", "أوبر"]),
    question("company", "airbnb", ["airbnb", "اير بي ان بي", "إير بي إن بي"]),
    question("company", "reddit", ["reddit", "ريديت"]),
    question("company", "github", ["github", "جيت هب", "قيت هب"]),
    question("company", "playstation", ["playstation", "بلايستيشن", "بلاي ستيشن"]),
    question("company", "cloudflare", ["cloudflare", "كلاودفلير", "كلاود فلير"]),
    question("company", "twitch", ["twitch", "تويتش"]),
    question("company", "telegram", ["telegram", "تليجرام", "تيليغرام"]),
    question("company", "whatsapp", ["whatsapp", "واتساب", "واتس اب"]),
    question("company", "pinterest", ["pinterest", "بنترست", "بينترست"]),
    question("company", "snapchat", ["snapchat", "سناب شات", "سناب"]),
    question("company", "steam", ["steam", "ستيم"]),
    question("company", "epicgames", ["epic games", "epicgames", "ايبك جيمز", "إيبك غيمز"]),
    question("company", "unity", ["unity", "يونيتي"]),
    question("company", "unrealengine", ["unreal engine", "انريل انجين", "أنريل إنجن"]),
    question("company", "meta", ["meta", "ميتا"]),
    question("company", "notion", ["notion", "نوشن"]),
    question("company", "dropbox", ["dropbox", "دروب بوكس", "دروبوكس"]),
    question("company", "zoom", ["zoom", "زوم"]),
    question("company", "figma", ["figma", "فيجما", "فجما"]),
  ],
};
